Fix bugs on get_ascending_area & get_descending_area
InseeFrLab/pynsee pull request #144
Opened 2023-05-15 09:19 UTC by tgrandje

* fix bug on url construction (if date is missing, "?" was missing from the URL)
* fix message on ValueError if area not found
* black formatting

2023-06-14 12:14 UTC, tfardet requested changes
Looks good overall, I'm just wondering about the hash function... is there a specific reason why you're not using hash on the URL?
If there is, then it would be better to write a hash function and call it in both functions rather than duplicate code.
Could you also merge the main branch again?

2023-06-14 13:26 UTC, tgrandje commented
@tfardet about _hash I did it according to other parts of the module (for instance, it is consistent with [that part](https://github.com/InseeFrLab/pynsee/blob/master/pynsee/localdata/get_geo_list.py#L68)).
(I think that most of the time, the URL is computed afterwards and after trying to access the cached file (for which you need the hashed value). It might be faster that way, but not by much...)

2023-06-14 13:31 UTC, tgrandje commented
@tfardet I think there are tests already : [here](https://github.com/InseeFrLab/pynsee/blob/master/tests/localdata/test_pynsee_localdata.py#L204) and [there](https://github.com/InseeFrLab/pynsee/blob/master/tests/localdata/test_pynsee_localdata.py#L195) ?

2023-06-14 15:06 UTC, tfardet commented
@tgrandje I understand, it just feels a bit bad to have two additional lines of code (repeated in two different functions) just to prepare a list which has only one purpose: to be used to compute a hash... but I guess it outside the scope of this PR.

Regarding the tests:  it would be good to have one with the ``type`` argument but without the ``date``, so we actually check that this bug does not occur anymore (in case someone make a revert from an old branch or whatever)

2023-06-17 23:16 UTC, hadrilec commented
@tfardet indeed if you dont mind I would prefer to make the merges myself, but your reviews are highly appreciated on my side as my review becomes just a routine check. Thanks again @tgrandje and @tfardet, great to have you on board ;)

2023-07-02 11:37 UTC, tfardet requested changes
@hadrilec I think the last change you made does not do what you actually wanted, can you check my proposed change?

2023-07-02 11:37 UTC, tfardet commented on tests/localdata/test_pynsee_localdata.py
> +            self.assertRaises(RequestException, get_area_list_test)
```suggestion
        with self.assertRaises(RequestException):
            get_area_list(area="regions", date="1900-01-01", update=True)
```

2023-07-02 19:57 UTC, hadrilec approved these changes
ok

2023-07-19 19:23 UTC, merged