Fix get_area_list case problem + black formatting
InseeFrLab/pynsee pull request #146
Opened 2023-05-15 16:49 UTC by tgrandje

Should resolve https://github.com/InseeFrLab/pynsee/issues/145

2023-05-16 07:09 UTC, tgrandje commented
Just added some more changes to get_area_list. To sum it up, the PR contains :

* a quick and dirty fix of area's case sensitive problem (which would happen with areas rightfully containing upper-case letters, for instance "collectivitesDOutreMer")
* make get_area_list consistent with get_geo_list about "date" argument : 
  * add the argument to the function 
  * change default behaviour (which until now used a "*" wildcard and so got all available data) to the same as get_geo_list : the default is now consistent with the API's documentation (ie. the current date)
* black formatting

2023-06-14 12:27 UTC, tfardet requested changes
Thanks for the bugfix!
Could you also add a test for these cases?

@hadrilec I'm not familiar with this INSEE data but I'm a bit surprised by the hardcoded date, is this something that will never change of will we see later entries in the future that would make it worth creating an issue to think about how to properly handle this?
(not relevant for that PR, obviously)

2023-06-14 12:27 UTC, tfardet commented on pynsee/localdata/get_area_list.py
> +    )
```suggestion
    filename = _hash(
        "".join(["get_area_list"] + list_available_area + [date or ""])
    )

```

2023-06-14 20:07 UTC, tgrandje commented
@tfardet that one should be ok now, though I didn't checked the behaviour of the tests. Those are covered in the automated tests directly runned on github, right ?

2023-06-15 07:25 UTC, tfardet requested changes
Almost there: you seem to have undone some of your previous hard work by reintegrating a print...

2023-06-15 07:25 UTC, tfardet commented on pynsee/localdata/get_area_list.py
> +            print(
something wrong happened here ^^

2023-06-15 07:48 UTC, tfardet approved these changes

2023-06-15 07:50 UTC, tgrandje commented
Sorry, my bad (I should have postponed it to this morning :-) ). Github desktop displayed some strange things while changing of computer this morning but this seems ok on Github (web).

2023-06-17 22:55 UTC, hadrilec commented
@tfardet 

> Thanks for the bugfix! Could you also pull from main branch and add a test for these cases?
> 
> @hadrilec I'm not familiar with this INSEE data but I'm a bit surprised by the hardcoded date, is this something that will never change of will we see later entries in the future that would make it worth creating an issue to think about how to properly handle this? (not relevant for that PR, obviously)

Indeed I agree, hard coded dates are far from being state-of-the-art. It is good to know that on paper local data API is still on a beta version. Then, some data update occurs every 5 five years so it is not a big deal to get some dates hard coded as long as the maintenance can keep up.

2023-06-17 23:10 UTC, merged

2023-06-17 23:11 UTC, hadrilec commented
Thanks a lot @tgrandje and @tfardet. Just merged after review.