Fix tests - steamline testing + multiprocessing backup
InseeFrLab/pynsee pull request #179
Opened 2023-12-26 10:46 UTC by hadrilec

2023-12-27 07:23 UTC, tfardet requested changes
I think there is a bug in the multiprocessing code (and I don't have time to debug it), please just wrap the original code in the try/except rather than the new one with the ``func_settings`` and ``func``, especially as this will eventually go away with #182 anyway.

Otherwise we're back at [3-hour tests](https://github.com/InseeFrLab/pynsee/actions/runs/7328879618/job/19973913463?pr=179).

2023-12-27 07:23 UTC, tfardet commented on pynsee/geodata/_get_geodata.py
> +            data_all = pd.concat(list_output).reset_index(drop=True)
do not include these changes, there is a bug somewhere which leads to the 4h-long tests

2023-12-27 07:23 UTC, tfardet commented on tests/macrodata/test_pynsee_macrodata.py
> +            #     self.assertTrue(test)
uncomment or remove

2023-12-27 07:23 UTC, tfardet commented on tests/macrodata/test_pynsee_macrodata.py
> +    #python test_pynsee_macrodata.py TestFunction.test_get_column_title_1
remove

2023-12-27 21:14 UTC, tfardet commented on pynsee/geodata/_get_geodata.py
> +                logger.warning(msg)
```suggestion
            try:
                irange = range(length)

                with multiprocessing.Pool(
                    initializer=_set_global_var,
                    initargs=(args,),
                    processes=Nprocesses,
                ) as pool:
                    list_output = list(
                        tqdm.tqdm(
                            pool.imap(_get_data_with_bbox2, irange),
                            total=len(list_bbox),
                        )
                    )
            except Exception:
                msg = "Multiprocessing failed in the geodata collection, " \
                      "using a traditional loop instead"

                logger.warning(msg)

                _set_global_var(args)
                list_output = []

                for p in tqdm.trange(length):
                    list_output.append(_get_data_with_bbox2(p))
```

2023-12-30 10:43 UTC, hadrilec commented
@tfardet, shall I merge?

2023-12-30 17:22 UTC, tfardet commented
@hadrilec I don't know... the tests still took 3h, for reasons that I don't understand... checking the coverage showed that the multiprocessing code was used, not the ``except`` block.

Could you first merge master into it and fix the conflicts? We'll see whether the 3h-long duration is still there (since you are using a branch on the pynsee account, I can't do it myself)

2025-01-24 15:46 UTC, closed without merging